title: Shivani Sachdeva 
logo: "/profile.png?raw=true"
description: >
 Software Engineer
  <br><br>
  <a href="mailto:sachdeva.shivani96@gmail.com">sachdeva.shivani96@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/shivani-sachdeva/">LinkedIn Profile</a>
  <br> 
  <a href="https://github.com/shivani-sachdeva">Github Profile</a>
theme: jekyll-theme-minimal
